# Generated by Django 3.0.3 on 2020-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200912_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=None, max_length=64, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
