# Generated by Django 3.0.3 on 2020-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200913_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(max_length=64, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
    ]
